// frontend/src/components/ContactForm.vue
<template>
  <div class="contact-section" id="contact-form">
    <h2 class="section-title">Get in Touch</h2>
    <p class="section-description">
      Sick of chasing down contractors who vanish faster than your budget? Whether you manage properties, build them from the ground up, or run commercial sites that demand real results — you're in the right place. At Platinum Enterprise Group, we don't cut corners (unless it's grass). We show up, we handle business, and we make you look like a genius for hiring us. From 24/7 maintenance and snow removal to full-scale renovations and upgrades, we do it all — and we do it properly. Fill out the form below and tell us what you need. No fluff. No excuses. Just professionals who actually pick up the phone, get the job done, and keep your properties running smoother than your tenant's excuses.
    </p>
    <form @submit.prevent="sendEmail" class="contact-form">
      <div class="form-group">
        <label for="from_name">Name</label>
        <input
          type="text"
          id="from_name"
          name="user_name"
          v-model="form.from_name"
          required
          placeholder="Your name"
        />
      </div>
      <div class="form-group">
        <label for="email">Email</label>
        <input
          type="email"
          id="email"
          name="user_email"
          v-model="form.email"
          required
          placeholder="Your email address"
        />
      </div>
      <div class="form-group">
        <label for="message">Message</label>
        <textarea
          id="message"
          name="message"
          v-model="form.message"
          required
          placeholder="Tell us about your project or inquiry"
          rows="5"
        ></textarea>
      </div>
      <button type="submit" class="submit-button">Send Message</button>
    </form>
  </div>
</template>

<script>
import emailjs from "emailjs-com";

export default {
  data() {
    return {
      form: {
        from_name: "",
        email: "",
        message: "",
      },
    };
  },
  mounted() {
    emailjs.init(import.meta.env.VITE_EMAILJS_PUBLIC_KEY);
  },
  methods: {
    sendEmail() {
      emailjs
        .send(
          import.meta.env.VITE_EMAILJS_SERVICE_ID, // Replace with your actual service ID
          import.meta.env.VITE_EMAILJS_TEMPLATE_ID, // Replace with your actual template ID
          {
            from_name: this.form.from_name,
            message: this.form.message,
            reply_to: this.form.email,
          }
        )
        .then(
          (response) => {
            console.log("Email sent successfully:", response);
            alert("Your message has been sent!");
            this.clearForm();
          },
          (error) => {
            console.error("Failed to send email:", error);
            alert("Oops! Something went wrong. Please try again.");
          }
        );
    },
    clearForm() {
      this.form.from_name = "";
      this.form.email = "";
      this.form.message = "";
    },
  },
};
</script>

<style scoped>
.contact-section {
  max-width: 800px;
  margin: 100px auto;
  padding: 2rem;
  font-family: 'Lora', serif;
}

.section-title {
  text-align: center;
  color: #C0C0C0; /* Platinum Silver */
  font-size: 2rem;
  font-weight: 700;
  margin-bottom: 1rem;
  letter-spacing: 0.5px;
  font-family: 'Cinzel', serif;
}

.section-description {
  text-align: center;
  color: #C0C0C0; /* Platinum Silver */
  opacity: 0.9;
  font-size: 1.1rem;
  line-height: 1.6;
  margin-bottom: 2.5rem;
  max-width: 600px;
  margin-left: auto;
  margin-right: auto;
  letter-spacing: 0.3px;
  font-family: 'Lora', serif;
}

.contact-form {
  max-width: 600px;
  margin: 0 auto;
  padding: 2rem;
  border: 1px solid #C0C0C0; /* Platinum Silver */
  border-radius: 8px;
  background-color: #1B1B1B; /* Graphite Black */
  color: #C0C0C0; /* Platinum Silver */
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  transition: all 0.3s ease;
}

.contact-form:hover {
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
  transform: translateY(-2px);
}

.form-group {
  margin-bottom: 1.5rem;
}

label {
  display: block;
  margin-bottom: 0.5rem;
  color: #C0C0C0; /* Platinum Silver */
  font-size: 0.9rem;
  font-weight: 500;
  letter-spacing: 0.3px;
}

input,
textarea {
  width: 100%;
  padding: 0.75rem;
  border: 1px solid #C0C0C0; /* Platinum Silver */
  border-radius: 4px;
  background-color: #000000;
  color: #C0C0C0; /* Platinum Silver */
  font-size: 1rem;
  transition: all 0.3s ease;
  font-family: 'Lora', serif;
}

input:focus,
textarea:focus {
  outline: none;
  border-color: #9aa0a6; /* Darker platinum for focus */
  box-shadow: 0 0 0 2px rgba(192, 192, 192, 0.1);
}

input::placeholder,
textarea::placeholder {
  color: rgba(255, 255, 255, 0.5);
}

textarea {
  resize: vertical;
  min-height: 120px;
}

.submit-button {
  background-color: #C0C0C0; /* Platinum Silver */
  color: #000000;
  border: none;
  border-radius: 4px;
  padding: 0.75rem 1.5rem;
  cursor: pointer;
  transition: all 0.3s ease;
  font-weight: 500;
  letter-spacing: 0.3px;
  font-size: 1rem;
  width: 100%;
  margin-top: 1rem;
}

.submit-button:hover {
  background-color: #9aa0a6; /* Darker platinum for hover */
  transform: translateY(-1px);
}

@media (max-width: 768px) {
  .contact-section {
    margin: 80px 1rem;
    padding: 1rem;
  }

  .section-title {
    font-size: 1.75rem;
  }

  .section-description {
    font-size: 1rem;
    margin-bottom: 2rem;
  }

  .contact-form {
    padding: 1.5rem;
  }

  input,
  textarea {
    font-size: 0.95rem;
  }
}
</style>

// react-components/ContactForm.jsx
import React, { useState, useEffect } from 'react';
import emailjs from 'emailjs-com';
import './ContactForm.css';

const ContactForm = () => {
  const [form, setForm] = useState({
    from_name: '',
    email: '',
    message: '',
  });

  useEffect(() => {
    // Initialize EmailJS
    if (import.meta.env.VITE_EMAILJS_PUBLIC_KEY) {
      emailjs.init(import.meta.env.VITE_EMAILJS_PUBLIC_KEY);
    }
  }, []);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setForm((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  const sendEmail = async (e) => {
    e.preventDefault();

    try {
      const response = await emailjs.send(
        import.meta.env.VITE_EMAILJS_SERVICE_ID,
        import.meta.env.VITE_EMAILJS_TEMPLATE_ID,
        {
          from_name: form.from_name,
          message: form.message,
          reply_to: form.email,
        }
      );

      console.log('Email sent successfully:', response);
      alert('Your message has been sent!');
      clearForm();
    } catch (error) {
      console.error('Failed to send email:', error);
      alert('Oops! Something went wrong. Please try again.');
    }
  };

  const clearForm = () => {
    setForm({
      from_name: '',
      email: '',
      message: '',
    });
  };

  return (
    <div className="contact-section" id="contact-form">
      <h1 className="section-title">
        Request a Free Quote - Property Maintenance Services in Cambridge, Kitchener & Waterloo
      </h1>
      <p className="section-description">
        Sick of chasing down contractors who vanish faster than your budget? Whether you manage properties in Cambridge, build them from the ground up in Kitchener, or run commercial sites in Waterloo that demand real results — you're in the right place. At Platinum Enterprise Group, we don't cut corners (unless it's grass). We show up, we handle business, and we make you look like a genius for hiring us. From 24/7 maintenance and snow removal to full-scale renovations and upgrades, we do it all — and we do it properly. Serving Cambridge, Kitchener, Waterloo, Waterloo Region, and throughout Southwestern Ontario. Fill out the form below and tell us what you need. No fluff. No excuses. Just professionals who actually pick up the phone, get the job done, and keep your properties running smoother than your tenant's excuses.
      </p>
      <form onSubmit={sendEmail} className="contact-form">
        <div className="form-group">
          <label htmlFor="from_name">Name</label>
          <input
            type="text"
            id="from_name"
            name="from_name"
            value={form.from_name}
            onChange={handleChange}
            required
            placeholder="Your name"
          />
        </div>
        <div className="form-group">
          <label htmlFor="email">Email</label>
          <input
            type="email"
            id="email"
            name="email"
            value={form.email}
            onChange={handleChange}
            required
            placeholder="Your email address"
          />
        </div>
        <div className="form-group">
          <label htmlFor="message">Message</label>
          <textarea
            id="message"
            name="message"
            value={form.message}
            onChange={handleChange}
            required
            placeholder="Tell us about your project or inquiry"
            rows="5"
          />
        </div>
        <button type="submit" className="submit-button">
          Send Message
        </button>
      </form>
    </div>
  );
};

export default ContactForm;
